"""HTML report rendering."""

from datetime import datetime
from pathlib import Path
from typing import Any

from .grouping import SEVERITY_ORDER, group_by_severity
from .models import ReportConfig


def render_finding_html(finding: Any, config: ReportConfig) -> str:
    """Render a single finding block in HTML."""
    severity_class = str(finding.severity).lower()
    parts = [
        f'<div class="finding {severity_class}" id="finding-{finding.id}">',
        f"<h3>{finding.title}</h3>",
        f'<span class="severity {severity_class}">{finding.severity.upper()}</span>',
        '<div class="field"><div class="field-label">Type</div>',
        f'<div class="field-value">{finding.attack_type}</div></div>',
        '<div class="field"><div class="field-label">Description</div>',
        f'<div class="field-value">{finding.description or "No description available"}</div></div>',
    ]

    if config.include_evidence and finding.evidence:
        parts.extend(
            [
                '<div class="field"><div class="field-label">Evidence</div>',
                f'<div class="evidence">{finding.evidence}</div></div>',
            ]
        )

    if config.include_remediation and finding.remediation:
        parts.extend(
            [
                '<div class="field"><div class="field-label">Remediation</div>',
                f'<div class="field-value">{finding.remediation}</div></div>',
            ]
        )

    parts.append("</div>")
    return "\n".join(parts)


def generate_html_report(
    report_dir: Path,
    state: Any,
    findings: list[Any],
    config: ReportConfig,
    executive_summary: str,
) -> Path:
    """Generate an HTML report file."""
    generated_at = datetime.now()
    grouped = group_by_severity(findings)

    html = f"""<!DOCTYPE html>
<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
<title>Penetration Test Report - {state.target or "Unknown"}</title>
<style>
body{{font-family:Arial,sans-serif;line-height:1.6;max-width:1100px;margin:0 auto;padding:20px;background:#f5f5f5;}}
.header{{background:#1f4d91;color:#fff;padding:28px;border-radius:8px;margin-bottom:24px;}}
.card{{background:#fff;padding:20px;border-radius:8px;margin-bottom:18px;box-shadow:0 1px 4px rgba(0,0,0,.08);}}
.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:16px 0;}}
.stat{{background:#fff;border-left:4px solid #1f4d91;padding:12px;border-radius:6px;}}
.finding{{background:#fff;padding:16px;margin:14px 0;border-left:4px solid #999;border-radius:6px;}}
.finding.critical{{border-left-color:#b91c1c;}} .finding.high{{border-left-color:#ea580c;}}
.finding.medium{{border-left-color:#ca8a04;}} .finding.low{{border-left-color:#15803d;}} .finding.info{{border-left-color:#0369a1;}}
.severity{{display:inline-block;padding:2px 9px;border-radius:999px;color:#fff;background:#444;font-size:.8em;font-weight:bold;}}
.severity.critical{{background:#b91c1c;}} .severity.high{{background:#ea580c;}} .severity.medium{{background:#ca8a04;color:#111;}}
.severity.low{{background:#15803d;}} .severity.info{{background:#0369a1;}}
.field-label{{font-size:.85em;font-weight:bold;color:#666;text-transform:uppercase;}} .evidence{{background:#f2f4f7;padding:10px;border-radius:4px;font-family:monospace;}}
</style></head><body>
<div class=\"header\"><h1>Penetration Test Report</h1><p><strong>Target:</strong> {state.target or "N/A"}<br>
<strong>Generated:</strong> {generated_at.strftime("%Y-%m-%d %H:%M:%S")}<br>
<strong>Phase:</strong> {state.current_phase}</p></div>
<div class=\"card\"><h2>Executive Summary</h2><p>{executive_summary}</p></div>
<div class=\"stats\">
<div class=\"stat\"><strong>Critical:</strong> {state.critical_count}</div>
<div class=\"stat\"><strong>High:</strong> {state.high_count}</div>
<div class=\"stat\"><strong>Medium/Low:</strong> {state.findings_count - state.critical_count - state.high_count}</div>
<div class=\"stat\"><strong>Total Findings:</strong> {len(findings)}</div>
</div>
<h2>Findings Summary</h2>
"""

    if findings:
        for severity in SEVERITY_ORDER:
            scoped = grouped[severity]
            if not scoped:
                continue
            html += f"<h3>{severity.upper()} ({len(scoped)})</h3>\n"
            for finding in scoped:
                html += render_finding_html(finding, config) + "\n"
    else:
        html += "<p>No findings recorded.</p>\n"

    html += (
        '<h2>Methodology</h2><div class="card"><p>Testing followed OWASP, PTES, and NIST SP '
        "800-115 guidance across reconnaissance, enumeration, vulnerability assessment, "
        "exploitation, post-exploitation, and reporting.</p></div>"
        f'<p style="color:#666;margin-top:30px;">Generated by ClawPwn at '
        f"{generated_at.strftime('%Y-%m-%d %H:%M:%S')}</p></body></html>"
    )

    report_file = report_dir / f"pentest_report_{generated_at.strftime('%Y%m%d_%H%M%S')}.html"
    report_file.write_text(html, encoding="utf-8")
    return report_file
