"""Markdown report rendering."""

from datetime import datetime
from pathlib import Path
from typing import Any

from .grouping import SEVERITY_ORDER, group_by_severity
from .models import ReportConfig


def render_finding_markdown(finding: Any, config: ReportConfig) -> str:
    """Render a finding as Markdown."""
    severity_marker = {
        "critical": "[CRITICAL]",
        "high": "[HIGH]",
        "medium": "[MEDIUM]",
        "low": "[LOW]",
        "info": "[INFO]",
    }.get(str(finding.severity).lower(), "[UNKNOWN]")

    lines = [
        f"#### {severity_marker} {finding.title}",
        "",
        f"**Severity:** {finding.severity.upper()}",
        f"**Type:** {finding.attack_type}",
        "",
        "**Description:**",
        str(finding.description or "No description available."),
        "",
    ]

    if config.include_evidence and finding.evidence:
        lines.extend(["**Evidence:**", "```", str(finding.evidence), "```", ""])

    if config.include_remediation and finding.remediation:
        lines.extend(["**Remediation:**", str(finding.remediation), ""])

    lines.extend(["---", ""])
    return "\n".join(lines)


def generate_markdown_report(
    report_dir: Path,
    state: Any,
    findings: list[Any],
    config: ReportConfig,
    executive_summary: str,
) -> Path:
    """Generate a Markdown report file."""
    generated_at = datetime.now()
    grouped = group_by_severity(findings)

    md = [
        "# Penetration Test Report",
        "",
        f"**Target:** {state.target or 'N/A'}",
        f"**Generated:** {generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Current Phase:** {state.current_phase}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        executive_summary,
        "",
        "## Findings Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| Critical | {state.critical_count} |",
        f"| High | {state.high_count} |",
        f"| Medium/Low | {state.findings_count - state.critical_count - state.high_count} |",
        f"| **Total** | **{len(findings)}** |",
        "",
        "## Detailed Findings",
        "",
    ]

    if findings:
        for severity in SEVERITY_ORDER:
            scoped = grouped[severity]
            if not scoped:
                continue
            md.append(f"### {severity.upper()} ({len(scoped)})")
            md.append("")
            for finding in scoped:
                md.append(render_finding_markdown(finding, config))
    else:
        md.extend(["*No findings recorded.*", ""])

    md.extend(
        [
            "## Methodology",
            "",
            "Testing followed OWASP, PTES, and NIST SP 800-115 guidance across reconnaissance,",
            "enumeration, vulnerability assessment, exploitation, post-exploitation, and reporting.",
            "",
            "---",
            "",
            f"Generated by ClawPwn at {generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
        ]
    )

    report_file = report_dir / f"pentest_report_{generated_at.strftime('%Y%m%d_%H%M%S')}.md"
    report_file.write_text("\n".join(md), encoding="utf-8")
    return report_file
